spring.application.name=spring-learn
server.port=8080
logging.level.org.springframework=INFO
logging.level.com.cognizant=DEBUG
logging.pattern.console=%d{dd-MM-yyyy} %d{HH:mm:ss.SSS} %-5p [%-20.20t] %-30.30logger{30} - %m%n
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
